# Generated by Django 5.0.6 on 2024-07-03 13:52
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="ip_adress",
            field=models.CharField(default="", max_length=120, null=True),
        ),
    ]
